[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "public"
[[plugins]]
  package = "@netlify/plugin-gatsby"
[functions]
  included_files = ["src/cms/config.json"]
[functions."puzzle"]
  included_files = ["src/cms/puzzle/**.json"]