site_url: "https://chicagomovietours.netlify.app"
logo_url: "https://chicagomovietours.netlify.app/icon.png"
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'
local_backend: true
media_folder: "static/data/uploads"
public_folder: "/data/uploads"
collections:
  - name: "game_data"
    label: "Game Data"
    identifier_field: "id"
    create: false
    extension: json
    files:
      - label: "Games"
        name: "games"
        file: "src/cms/games.json"
        fields:
          - label: "Games"
            name: "games"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - {
                  label: "ID",
                  name: "game_id",
                  widget: "number",
                  min: 0,
                  value_type: "int",
                  hint: 'Unique ID, use for "Next Puzzle ID"',
                }
              - { label: "Description", name: "description", widget: "string" }
              - label: "Access Codes"
                name: "access_codes"
                widget: "list"
                field:
                  {
                    label: "Access Code",
                    name: "access_code",
                    widget: "string",
                  }
              - label: "Puzzles"
                name: "puzzles"
                widget: "list"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "string",
                      hint: "Shown above everything else",
                    }
                  - {
                      label: "Puzzle ID",
                      name: "id",
                      widget: "number",
                      min: 0,
                      value_type: "int",
                      hint: "Unique ID - 0 is first - the Next button will go to the next ID (0 -> 1)",
                    }
                  - { label: "Image", name: "image", widget: "image" }
                  - {
                      label: "Hint",
                      name: "hint",
                      widget: "text",
                      hint: "Displayed alongside answer box",
                    }
                  - {
                      label: "Answer",
                      name: "answer",
                      widget: "string",
                      hint: "This will be matched exactly when input, make sure your hint describes how to input your answer.",
                    }
                  - {
                      label: "Correct Answer Text",
                      name: "answer_correct_text",
                      widget: "text",
                      required: false,
                      hint: "Displayed upon correct answer being entered",
                    }
